import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/about.module.scss'
import TopBar from "../../components/topbar";
import {useState} from "react";
import {useRouter} from "next/router";
import OverTime from "../../components/OverTime";

export default function Home() {
    const [panelState, setpanelState] = useState(0);
    const router = useRouter()
    return (
        <div className={styles.container}>
            <Head>
                <title>漾</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;"/>
            </Head>
            <TopBar title={"个人中心"}/>
            <div className={styles.info}>
                <Image src={require("/public/img/about/about.png")} alt={"about"}/>
            </div>
            <div className={styles.panel}>
                {imgDisp(panelState)}
            </div>

            <div className={styles.btn1} onClick={() => {
                setpanelState(0);
            }}/>
            <div className={styles.btn2} onClick={() => {
                setpanelState(1);
            }}/>
            <div className={styles.settingbtn} onClick={() => {
                router.push("/about/setting");
            }}/>
            <div className={styles.tagbtn} onClick={() => {
                router.push("/about/airtag");
            }}/>
            <OverTime/>

        </div>
    )
}

function imgDisp(a) {
    if (a === 0) {
        return <Image src={require("/public/img/about/info.png")} alt={"connnect1"}
        />
    } else if (a === 1) {
        return <Image src={require("/public/img/about/healthInfo.png")} alt={"connect1"}
        />
    }
}