import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/app.module.scss'
import Topbar from "../components/topbar"
import Link from "next/link";
import OverTime from "../components/OverTime";

export default function Home() {

    return (
        <div className={styles.container}>
            <Head>
                <title>漾</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;"/>
            </Head>
            <Topbar title={"产品服务"}/>
            <div className={styles.content}>
                <div className={styles.yangsheng}>
                    <Image src={require("../public/img/app/yangsheng.png")} alt={"yangshen"}/>
                </div>
                <div className={styles.yundong}>
                    <Image src={require("../public/img/app/yundon.png")} alt={"yundong"}/>
                    <div className={styles.lasheng}>
                        <Link href="/stretch">
                            <a>
                                <Image src={require("../public/img/app/lashen.png")} alt={"lashen"}/>
                            </a>
                        </Link>
                    </div>
                </div>
                <div className={styles.qita}>
                    <Image src={require("../public/img/app/qita.png")} alt={"qita"}/>

                </div>
            </div>
            <OverTime/>

        </div>
    )
}
