import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import {getDate, getLunar, getTime} from "../components/utils";
import Link from "next/link";
import {useEffect, useState} from "react";
import {useRouter} from "next/router";

export default function Home() {
    const router = useRouter();
    const [t, setT] = useState({time: "", lunar: "", date: ""})
    useEffect(() => {
        setT({time: getTime(), lunar: getLunar(), date: getDate()})

        setInterval(() => {
            setT({time: getTime(), lunar: getLunar(), date: getDate()})
        }, 1000)
    }, [])
    const [c, setc] = useState(1);
    return (
        <div className={styles.container}>
            <Head>
                <title>漾</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;"/>
            </Head>
            <div className={styles.timeBar}>
                <div className={styles.left}> {t.time}</div>
                <div className={styles.mid}/>

                <div className={styles.right}>
                    <div className={styles.top}>{t.lunar}</div>
                    <div className={styles.bottom}>{t.date}</div>
                </div>
            </div>
            <div className={styles.content}>
                <div className={styles.greeting}> 早上好，王建国</div>
                <div> 近期注意身体健康</div>
            </div>
            <div className={styles.userInfo}>
                <div className={styles.imgBg} onClick={() => {
                    router.push("/about");
                }}>
                    <Image src={require("../public/img/index/user.png")} alt={"../public/img/index/user.png"}/>
                </div>
                <div className={styles.text}>
                    <div className={styles.heartBeat}>128</div>
                    <div className={styles.tmp}>37.5</div>
                    <div className={styles.figer}>良好</div>
                </div>

            </div>
            <div className={styles.menu}>
                <div className={styles.products}>
                    <Link href={"/apps"}>
                        <a>
                            <Image src={require("../public/img/index/product.png")} alt={"product"}/>
                        </a>
                    </Link>
                </div>
                <div className={styles.community}>
                    <Link href={"/community"}>
                        <a>
                            <Image src={require("../public/img/index/community.png")} alt={"community"}/>
                        </a>
                    </Link>
                </div>
            </div>
            <div className={styles.wifiSetting} onClick={() => {
                setc(c + 1)
                if (c > 5) {
                    router.push("/login")
                }
            }}/>
        </div>
    )
}
