import Head from 'next/head'
import Image from 'next/image'

import {useEffect, useState} from "react";
import {useRouter} from 'next/router'
import mqtt from "mqtt";

let client;
export default function Home() {
    const [state, setState] = useState("0")
    const router = useRouter()
    const [c, setc] = useState(2);
    useEffect(() => {
        // const client = mqttConnect();
        const options = {
            // Clean session
            clean: true,
            clientId: 'emqx_tsdfsdtag',
            username: 'admin',
            password: 'pubilc',
            reconnectPeriod: 1000,
            connectTimeout: 30 * 1000,
        }
        client = mqtt.connect('ws://192.168.3.3:8083/mqtt', options)

        return () => {
            client.end()
        }
    }, [])


    function send100() {
        client.publish('stretch', '100')
    }
    function send111() {
        client.publish('stretch', '111')
    }
    function send222() {
        client.publish('stretch', '222')
    }



    return (
        <div style={{display: "flex", justifyContent: "center", alignItems: "center", height: "100vh"}}>
            <Head>
                <title>漾</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <button onClick={() => {
                send100()
            }} style={{width: "200px", height: "100px"}}>100
            </button>

            <button onClick={() => {
                send111()
            }} style={{width: "200px", height: "100px"}}>111
            </button>
            <button onClick={() => {
                send222()
            }} style={{width: "200px", height: "100px"}}>222
            </button>


        </div>
    )
}

