import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import {getDate, getLunar, getTime} from "../components/utils";

import {useRouter} from "next/router";
import {useState} from "react";

export default function Home() {
    const router = useRouter();
    const [c, setc] = useState(2);
    return (
        <div className={styles.container}>
            <Head>
                <title>漾</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;"/>
            </Head>
            < video src={require('/public/video.mp4')} width={1080} height={1920} loop autoPlay
                    className={styles.videos}/>
            <div className={styles.videoBack} onClick={() => {
                setc(c + 1)
                if (c > 3) {
                    router.push("/")
                }
            }}/>
        </div>
    )
}
