import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/stretch.module.scss'
import TopBar from "../../components/topbar";
import {mqttConnect} from "../../components/utils";
import {useEffect, useState} from "react";
import {useRouter} from 'next/router'
import mqtt from "mqtt";
import OverTime from "../../components/OverTime";

export default function Home() {
    const [state, setState] = useState("0")
    const router = useRouter()
    const [c, setc] = useState(2);
    useEffect(() => {
        const timeout = setTimeout(() => {
            router.push("/stretch/info")
        }, 2000)
        return () => {
            clearTimeout(timeout)
        }
    }, [])
    return (
        <div className={styles.container}>
            <Head>
                <title>漾</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <TopBar title={"漾-Stretch"}/>
            <div className={styles.connect}>
                <Image src={require("../../public/img/stretch/connect3.png")} alt={"connnect1"}
                />
            </div>
            {/*<OverTime/>*/}

        </div>
    )
}
